@baseUrl = http://127.0.0.1:800/api/admin
@token = {{login.response.body.token}}

# 系统 - 管理员登陆
# @name login
POST {{baseUrl}}/token
content-type: application/json

{
    "type": "password",
    "username": "admin",
    "password": "123456"
}


###
#CRUD - CRUD列表
GET {{baseUrl}}/crud/product_brand
Authorization: Bearer {{token}}

###
#CRUD - CRUD读取
GET {{baseUrl}}/crud/product_brand/1
Authorization: Bearer {{token}}


###
#CRUD - CRUD更新
PUT {{baseUrl}}/crud/product_brand/1
Authorization: Bearer {{token}}


###
#REST - GET操作
GET {{baseUrl}}/rest/product_brand/act/1
Authorization: Bearer {{token}}

###
#REST - POST操作
POST {{baseUrl}}/rest/product_brand/act/1
Authorization: Bearer {{token}}

###
#系统 - 获取高级表格(ProTable)的schema描述
GET {{baseUrl}}/schema/protable/config
Authorization: Bearer {{token}}

###
#系统 - 获取表单(Formily)的schema描述
GET {{baseUrl}}/schema/formily/setting
Authorization: Bearer {{token}}

###
#系统 - 获取管理员列表
GET {{baseUrl}}/admin
Authorization: Bearer {{token}}

###
#系统 - 获取字典列表
GET {{baseUrl}}/dicts
Authorization: Bearer {{token}}

###
#系统 - 获取字典条目
GET {{baseUrl}}/dicts/field_component

###
#系统 - 创建云存储直传token
POST {{baseUrl}}/upload/token/logo
Authorization: Bearer {{token}}
